version: '3.8'

services:
  back:
    image: docker.io/library/rust:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app/back
    command: ["cargo", "run"]

  front:
    image: docker.io/library/node:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app/front
    command: ["npm", start]