version: '3.8'

services:
  back:
    image: node:latest
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    working_dir: /app/new-back
    command: npm run dev
    networks:
      - mynet

  front:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app/front
    command: ["npm", start]
    networks:
      - mynet

networks:
  mynet: