version: '3.8'

services:
  back:
    image: docker.io/library/rust:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app/back
    command: ["cargo", "run", "--release"]

  front:
    image: nginx
    volumes:
      - ./front/dist:/usr/share/nginx/html:ro
      - ./front/nginx.conf:/etc/nginx/nginx.conf
      # - ./cert.pem:/etc/nginx/cert.pem
      # - ./key.pem:/etc/nginx/cert.key
    ports:
    - "3000:3000"
    environment:
    - NGINX_HOST=0.0.0.0
    - NGINX_PORT=3000